version: '3'
services:
  app:
    build:
      context: .
      args:
        - UPSTAGE_API_KEY=${UPSTAGE_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - UPSTAGE_API_KEY=${UPSTAGE_API_KEY}
